# SPDX-FileCopyrightText: 2025 Chen Linxuan <me@black-desk.cn>
#
# SPDX-License-Identifier: MIT

name: 'clean-action'
description: 'GitHub Action for running the clean binary built with Rust using the provided Containerfile.'
author: 'black-desk'
inputs:
  extra_args:
    description: 'Arguments to pass to the clean binary (as a single string, e.g. "--foo bar --baz")'
    required: false
    default: ''
outputs:
  json:
    description: 'JSON output'
  yaml:
    description: 'YAML output'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/black-desk/clean:master'
  entrypoint: '/usr/bin/env'
  args:
    - sh
    - -c
    - |
      set -e
      git config --global --add safe.directory /github/workspace
      export RUST_BACKTRACE=1
      echo 'json<<EOF' >> "$GITHUB_OUTPUT"
      /opt/io.github.black-desk/clean/bin/clean --json ${{ inputs.extra_args }} >> "$GITHUB_OUTPUT" || true
      echo 'EOF' >> "$GITHUB_OUTPUT"
      echo 'yaml<<EOF' >> "$GITHUB_OUTPUT"
      /opt/io.github.black-desk/clean/bin/clean --yaml ${{ inputs.extra_args }} >> "$GITHUB_OUTPUT" || true
      echo 'EOF' >> "$GITHUB_OUTPUT"
      /opt/io.github.black-desk/clean/bin/clean ${{ inputs.extra_args }} >> "$GITHUB_STEP_SUMMARY"

branding:
  icon: 'check-circle'
  color: 'blue'
